name: 'Publish resources to Preset workspace'

env:
  WORKSPACE: https://49437123.us1a.app.preset.io/

  DBT_PROFILES_DIR: ./
  DBT_GOOGLE_PROJECT_DEV: ${{ secrets.DBT_GOOGLE_PROJECT_DEV }}
  DBT_GOOGLE_BIGQUERY_DATASET_DEV: ${{ secrets.DBT_GOOGLE_BIGQUERY_DATASET_DEV }}
  # The DBT_GOOGLE_BIGQUERY_KEYFILE_DEV secret will be written to a json file below
  DBT_GOOGLE_BIGQUERY_KEYFILE_DEV: ./dbt-service-account.json

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  publish:
    name: 'Publish resources'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - name: 'Checkout CLI'
      uses: actions/checkout@v3
      with:
        repository: preset-io/backend-sdk
        path: preset-cli

    - name: 'Install CLI'
      run: |
        cd preset-cli
        pip install .
        cd ..

    - name: 'Install dbt'
      run: |
        pip install dbt-core dbt-bigquery

    - name: 'Checkout'
      uses: actions/checkout@v3

    - name: 'Compile manifest'
      run: |
        cd jaffle_shop
        dbt compile
        cd ..
        
    - name: 'Authenticate using service account'
      run: 'echo "$KEYFILE" > ./dbt-service-account.json'
      env:
        KEYFILE: ${{secrets.DBT_GOOGLE_BIGQUERY_KEYFILE_DEV}}

    - name: 'Publish resources'
      env:
        PRESET_API_TOKEN: ${{ secrets.PRESET_API_TOKEN }}
        PRESET_API_SECRET: ${{ secrets.PRESET_API_SECRET }}
      run: |
        preset-cli --workspaces=${WORKSPACE} superset sync dbt \
          ./dbt-integration-blog-post/jaffle_shop/target/manifest.json \
          --project=jaffle_shop --target=dev --import-db
